language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/vinceallenvince/Burner.git
  - secure: "jiBAkOWvD9bqD0gUAaI8Nn8qXEC+PIGu0Qr2mvIuZgLRoqFuubgsnA9yW7CEepdbBRtK3LDr56zW454g1/LW/dkuU2AizqsFNkCCUtC4vc17dErcL1EiDlyenApkbhsWtP0CZoVL0yTRtm6ekihU2qqM+QZq79VuPVMNkQX81lo="
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli
after_success: grunt release
before_deploy: "echo 'ready?'"
deploy:
  provider: releases
  api_key:
    secure: W5kwsHMWpoH36mqSn3XkAxTIzRke59vdIbP/AsHRShVTg4yr5Nbb/vpKq9PLvAlr8fjNAuOr09SXXvezvW1EZb0NMxY/LLIFfo7+L72zxKZtR65yLUwqRwI9fV77Yo1IrKtVytRohMdxcs2rWes23hey2Vt97Lzo8rJT+PU5isk=
  file:
  - release/Burner.min.js
  - release/Burner.min.css
  on:
    repo: vinceallenvince/Burner
after_deploy:
- "echo 'done!'"
- ./deploy-gh-pages.sh
